kind: pipeline
name: default
type: docker

steps:
  - name: nextcloud:21
    image: nextcloud:21
    commands:
      - curl -sSLo /usr/local/bin/composer https://getcomposer.org/download/latest-stable/composer.phar
      - chmod +x /usr/local/bin/composer
      - composer install
      - composer run lint
      - composer run cs:check
      - composer run psalm:check

  - name: nextcloud:27
    image: nextcloud:27.0.0
    commands:
      - curl -sSLo /usr/local/bin/composer https://getcomposer.org/download/latest-stable/composer.phar
      - chmod +x /usr/local/bin/composer
      - composer install
      - composer run lint
      - composer run cs:check
      - composer run psalm:check
